"""v2 postgres pgvector

Revision ID: 20260803_0001
Revises: 
Create Date: 2026-08-03 22:20:17.825258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = "20260803_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concepts_topic'), 'concepts', ['topic'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('concept_dependencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prerequisite_id', sa.Integer(), nullable=False),
    sa.Column('dependent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dependent_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_dependencies_dependent_id'), 'concept_dependencies', ['dependent_id'], unique=False)
    op.create_index(op.f('ix_concept_dependencies_prerequisite_id'), 'concept_dependencies', ['prerequisite_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.Enum('ask', 'quiz', 'review', name='ck_conversations_mode', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('material_scope', postgresql.JSONB(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_memory_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('learning_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_subject', sa.String(length=200), nullable=True),
    sa.Column('review_goal', sa.Text(), nullable=True),
    sa.Column('weak_concepts', postgresql.JSONB(), nullable=False),
    sa.Column('frequent_questions', postgresql.JSONB(), nullable=False),
    sa.Column('active_materials', postgresql.JSONB(), nullable=False),
    sa.Column('preferences', postgresql.JSONB(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_profiles_user_id'), 'learning_profiles', ['user_id'], unique=True)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.Enum('pdf', 'docx', 'pptx', 'image', name='ck_materials_file_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('processing_status', sa.Enum('pending', 'processing', 'ready', 'failed', name='ck_materials_processing_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.String(length=1000), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('hash', sa.String(length=128), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_hash'), 'materials', ['hash'], unique=False)
    op.create_index('ix_materials_user_created', 'materials', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_materials_user_id'), 'materials', ['user_id'], unique=False)
    op.create_index('ix_materials_user_status', 'materials', ['user_id', 'processing_status'], unique=False)
    op.create_table('quiz_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('material_scope', postgresql.JSONB(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('total_time_seconds', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='ck_quiz_sessions_difficulty', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_sessions_user_id'), 'quiz_sessions', ['user_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='ck_conversation_messages_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('material_scope', postgresql.JSONB(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_table('material_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('text_preview', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('lexical_tokens', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(dim=1024), nullable=True),
    sa.Column('embedding_model', sa.String(length=200), nullable=True),
    sa.Column('metadata', postgresql.JSONB(), nullable=False),
    sa.Column('embedding_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_chunks_chunk_id'), 'material_chunks', ['chunk_id'], unique=True)
    op.create_index('ix_material_chunks_embedding_hnsw', 'material_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.execute(
        "CREATE INDEX ix_material_chunks_lexical_search "
        "ON material_chunks USING gin "
        "(to_tsvector('simple', lexical_tokens))"
    )
    op.create_index(op.f('ix_material_chunks_material_id'), 'material_chunks', ['material_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_session_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('multiple_choice', 'fill_blank', name='ck_questions_question_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('options', postgresql.JSONB(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='ck_questions_difficulty', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('concept', sa.String(length=100), nullable=True),
    sa.Column('source_chunk_ids', postgresql.JSONB(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_session_id'], ['quiz_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_quiz_session_id'), 'questions', ['quiz_session_id'], unique=False)
    op.create_table('answer_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('quiz_session_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('student_answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_spent_seconds', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_session_id'], ['quiz_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_records_question_id'), 'answer_records', ['question_id'], unique=False)
    op.create_index(op.f('ix_answer_records_quiz_session_id'), 'answer_records', ['quiz_session_id'], unique=False)
    op.create_index(op.f('ix_answer_records_user_id'), 'answer_records', ['user_id'], unique=False)
    op.create_table('mistake_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('source_question_id', sa.String(length=128), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('concept', sa.String(length=100), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('wrong_answer', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('source_chunk_ids', postgresql.JSONB(), nullable=False),
    sa.Column('source_material', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_wrong_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correction_note', sa.Text(), nullable=False),
    sa.Column('mastered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_history', postgresql.JSONB(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mistake_records_public_id'), 'mistake_records', ['public_id'], unique=True)
    op.create_index(op.f('ix_mistake_records_question_id'), 'mistake_records', ['question_id'], unique=False)
    op.create_index(op.f('ix_mistake_records_source_question_id'), 'mistake_records', ['source_question_id'], unique=False)
    op.create_index(op.f('ix_mistake_records_user_id'), 'mistake_records', ['user_id'], unique=False)
    op.create_index('ix_mistakes_user_concept', 'mistake_records', ['user_id', 'concept'], unique=False)
    op.create_index('ix_mistakes_user_status_review', 'mistake_records', ['user_id', 'status', 'next_review_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mistakes_user_status_review', table_name='mistake_records')
    op.drop_index('ix_mistakes_user_concept', table_name='mistake_records')
    op.drop_index(op.f('ix_mistake_records_user_id'), table_name='mistake_records')
    op.drop_index(op.f('ix_mistake_records_source_question_id'), table_name='mistake_records')
    op.drop_index(op.f('ix_mistake_records_question_id'), table_name='mistake_records')
    op.drop_index(op.f('ix_mistake_records_public_id'), table_name='mistake_records')
    op.drop_table('mistake_records')
    op.drop_index(op.f('ix_answer_records_user_id'), table_name='answer_records')
    op.drop_index(op.f('ix_answer_records_quiz_session_id'), table_name='answer_records')
    op.drop_index(op.f('ix_answer_records_question_id'), table_name='answer_records')
    op.drop_table('answer_records')
    op.drop_index(op.f('ix_questions_quiz_session_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_material_chunks_material_id'), table_name='material_chunks')
    op.execute("DROP INDEX IF EXISTS ix_material_chunks_lexical_search")
    op.drop_index('ix_material_chunks_embedding_hnsw', table_name='material_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_material_chunks_chunk_id'), table_name='material_chunks')
    op.drop_table('material_chunks')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_quiz_sessions_user_id'), table_name='quiz_sessions')
    op.drop_table('quiz_sessions')
    op.drop_index('ix_materials_user_status', table_name='materials')
    op.drop_index(op.f('ix_materials_user_id'), table_name='materials')
    op.drop_index('ix_materials_user_created', table_name='materials')
    op.drop_index(op.f('ix_materials_hash'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_learning_profiles_user_id'), table_name='learning_profiles')
    op.drop_table('learning_profiles')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_concept_dependencies_prerequisite_id'), table_name='concept_dependencies')
    op.drop_index(op.f('ix_concept_dependencies_dependent_id'), table_name='concept_dependencies')
    op.drop_table('concept_dependencies')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_concepts_topic'), table_name='concepts')
    op.drop_table('concepts')
    # ### end Alembic commands ###
